# Generated by Django 4.2.6 on 2023-11-03 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elearning_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('profile_pic', models.ImageField(blank=True, upload_to=elearning_app.models.path_and_rename, verbose_name='Profile Picture')),
                ('user_type', models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student')], default='Student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
